name: Jobs Configuration Matrix

on:
  workflow_dispatch:

jobs:
  job_1:
    strategy:
      # abort matrix execution when one jobs fails
      fail-fast: false
      max-parallel: 3
      # loop through os_version and node_version list - 6 jobs
      matrix:
        os_version: [macos-latest, ubuntu-latest]
        node_version: [12, 14, 16]
    name: My first job
    runs-on: ${{ matrix.os_version }}
    steps:
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node_version }}
